### ISSUE TITLE
Datepicker closing

### ISSUE THREAD

**Issue by SvetlanaMuravlova** [valor-software/ng2-bootstrap#6536]
When cycling the time it closes the popup with datepicker every time. so customers should open the popup a lot of times to select the correct time. This is taking very long to fix.

**Describe the solution you'd like**
Add config property to avoid breaking changes with native behavior of datepicker

**Comment by anilsanaka** [comment]
Hi @SvetlanaMuravlova - Issue is not fixed with setting keepDatepickerOpened : true. 

https://ngx-bootstrap-demo--pr6537-fix-date-time-picker-bwqnpgug.web.app/ngx-bootstrap/#/components/datepicker?tab=overview#date-initial-state

Here are my observations.

### **Date Picker with Time**  :  
      1. First time Open - Cycling on time arrows is dismissing/ closing the picker. Issue is still there.
      2. Second time open / consecutive Open - Cycling on time arrows , the picker stays. It is working . 
     
### **Date _Range_ Picker with Time** : 
      1. First time Open -  
           Cycling "From Time" - Picker Stays
           Cycling "To Time" - Picker dismisses/closes automatically
      2. Second time / consecutive Open - Cycling on time arrows , the picker stays. It is working 
      
As per my understanding second time it is working because Today's date is automatically selected even if we dont select date. You can see this by reopening the picker. Todays date is comming as selected. Which means on closing the picker automatically todays date is selected.

Till ngx-bootstrap: 8.0.0 version this behaviour is working fine and it was broken in ngx-bootstrap:9.0.0

**Comment by SvetlanaMuravlova** [comment]
@anilsanaka , yeah, you are right, it works in this way, cause when you set time at first without any date it sets the current date, as default because of it datepicker closes, it is native behavior. So you should set the date  and then you can change the time. If you need time without date you can use only timepicker.

**Comment by anilsanaka** [comment]
Hi @SvetlanaMuravlova - Date Picker with Time when it is first time open selecting date or cycling arrows is closing the picker. Is this behavior changed after 9.0.0 version only ? because we see it was working till 7.12 version.

Below is the behaviour in 7.12 : 
Clicking on Date without selecting time - Date picker dismisses and default system time is set.
Clicking/Cycling on Time without selecting Date - Date Picker remains and waits for setting time.

Below is the behaviour in 9.0.0
Clicking on Date without selecting time - Date picker dismisses . This is as expected as 7.1.2 
Clicking/Cycling on Time without selecting Date - Date Picker dismisses. This is not as expected. This is a regression defect from 7.1.2

Setting keepDatepickerOpened : true will make it work only from second time onwards. But for first time open of datepicker we still see the dismiss issue.

This functionality is broken in the later versions. Can you please validate from your end once.

**Comment by SvetlanaMuravlova** [comment]
@anilsanaka , hi) thank you for using our lib) 

in version 7.12  it didn't wait for some changes, there was a bug with date updates, then this bug was fixed and we got native behaviour of the component. Now the first closing of datepicker is because of setting first date, you aren't able to set time without date, in this way you should use timepicker without datepicker

**Comment by omar-dev-amrk** [comment]
Hey, I'm having trouble keeping the date range picker open, despite setting `keepDatepickerOpened: true`.
What am I missing here?

When selecting the first then second date, I want the picker to remain open for time modifications. How to achieve this?
```
ngx-bootstrap@10.3.0
angular@15
```

**Comment by omar-dev-amrk** [comment]
I added a question on Stackoverflow if anybody willing to answer there:
https://stackoverflow.com/questions/75671138/how-to-keep-the-date-range-with-time-range-picker-open-after-setting-the-dates

**Comment by gibahjoe** [comment]
This issue should not be closed since its not fixed as specified above as specified here

https://github.com/valor-software/ngx-bootstrap/issues/6536#issuecomment-1357364582

**Comment by antonisradiusfintech** [comment]
Agree. This does not work for sure in the latest version. What we need is to keep it open until we click somewhere else in the screen or even have an OK button. The way it works now it is not user friendly at all with very bad UX

**Comment by pantonis** [comment]
Agree. This does not work for sure in the latest version. What we need is to keep it open until we click somewhere else in the screen or even have an OK button. The way it works now it is not user friendly at all with very bad UX

**Comment by GGomes2710** [comment]
Any update regarding this?

https://github.com/valor-software/ngx-bootstrap/issues/6536#issuecomment-1357364582
